config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'
  devise_for :users
  resources :tasks
  resources :favorites, only: [:create, :destroy]
  resources :categories, only: [:index]

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :point_value, :lesson_number, presence: true

  scope :started, -> { where.not(started_on: nil) }
  scope :not_started, -> { where(started_on: nil) }
  scope :completed, -> { where.not(completed_on: nil) }
  scope :incomplete, -> { where(completed_on: nil) }
  scope :not_paused, -> { where(paused: false) }

  before_save :unpause_completes_and_not_starteds
  after_save :pause_other_current_tasks

  include TaskShared

  def self.by_date
    order('completed_on DESC')
  end

  def velocity
    previous_task = Task.where('paused = ? AND completed_on <= ?', false, started_on).last
    backfill = Task.new(completed_on: Date.today, started_on: Date.yesterday, point_value: 1, name: 'filler')

    previous_task = backfill if previous_task == nil

    days_to_finish = (previous_task.completed_on - previous_task.started_on).to_i

    if days_to_finish == 0
      previous_task.point_value / 1
    else
      previous_task.point_value / days_to_finish
    end
  end

  def projected_completion
    velocity = current_velocity(Proc.new { Task.completed })
    remaining_days = (point_value / velocity).to_i
    started_on + remaining_days
  end

  def days_spent
    if started_on && completed_on
      (completed_on - started_on).to_i
    elsif started_on
      (Date.today - started_on).to_i
    else
      'TBD'
    end
  end

  def complete?
    completed_on != nil
  end

  def started?
    started_on != nil
  end

  def paused?
    paused == true
  end

  def current?
    started? && (complete? == false)
  end

  def pause_other_current_tasks
    if started? && !complete? && !paused?
      currently_active_tasks = Task.started.incomplete.not_paused.to_a - [self]
      currently_active_tasks.each do |task|
        task.update_attributes(paused: true)
      end
    end
  end

  def unpause_completes_and_not_starteds
    unpause_completes
    unpause_not_starteds
  end

  def favorite!
    self.favorite = true
    self.save!
  end

  def unfavorite!
    self.favorite = false
    self.save!
  end

  private

  def unpause_completes
    if complete? && paused?
      self.paused = false
    end
  end

  def unpause_not_starteds
    if !started? && paused?
      self.paused = false
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:edit, :update, :destroy]
  before_action :set_task_set, only: [:index, :create, :update, :destroy]
  before_action :require_admin

  def index
  end

  def new
    @task = Task.new
    respond_to :js
  end

  def create
    @task = Task.new(task_params)
    @task.save
    # flash.notice = "Hooray! '#{@task.name}' has been added to the docket!"
    respond_to :js
  end

  def edit
    respond_to :js
  end

  def update
    @task.update(task_params)
    respond_to :js
  end

  def destroy
    @task.delete
    # flash.notice = "As you wish. '#{@task.name}' has been deleted."
    respond_to :js
  end

  private

  def task_params
    params.require(:task).permit(:name, :point_value, :started_on, :completed_on, :paused, :favorite, :lesson_number, :category_id, :description, :url)
  end

  def set_task
    @task = Task.find(params['id'])
  end

  def set_task_set
    @task_set = TaskSet.new(Task.all)
  end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  def completion_status_class(task)
    if task.paused? && !task.complete?
      'paused'
    elsif task.current?
      'current-task'
    elsif task.complete?
      'complete'
    else
      'incomplete'
    end
  end

  def display_start_date(task)
    task.started? ? task.started_on : 'TBD'
  end

  def display_end_date(task)
    if task.complete?
      task.completed_on
    elsif task.started?
      "projected #{task.projected_completion}"
    else
      'TBD'
    end
  end

  def display_velocity(task)
    task.started? ? task.velocity : 'TBD'
  end

  def display_task_set_velocity(set)
    set.current_velocity.to_i
  end

  def display_task_set_projected_completion_date(set)
    set.projected_completion_date.to_s(:long)
  end

  def toggle_favorite(task)
    if task.favorite
      # Show full star and link to un-fave
      link_to raw("<i class='fa fa-star'></i>"), favorite_path(task), remote: true, method: :delete
    else
      # Show hollow star and link to fave
      link_to raw("<i class='far fa-star'></i>"), favorites_path(id: task.id), remote: true, method: :post
    end
  end

  def render_task_set(header_name, task_set, dom_id)
    unless task_set.empty?
      raw("<div id='#{dom_id}'>
            <h2>#{header_name}</h2>
            #{render partial: 'task', collection: task_set}
          </div>")
    end
  end

end

app/views/tasks/_edit.html.erb
<hr />
<div class="right">
  <%= link_to 'Cancel', tasks_path, class: button_classes %>
</div> <!-- right -->

<%= render partial: 'form', locals: {task: task} %>

app/views/tasks/_error_messages.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for(task, remote: true) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="field col-sm-10">
      <%= f.label :name, "Name*" %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="field col-sm-2 checkbox">
      <%= f.label :favorite %><br>
      <%= f.check_box :favorite %>
    </div>
  </div><!-- row -->

  <div class="field">
    <%= f.label :category_id, "Category*" %><br>
    <%= f.collection_select(:category_id, Category.all.order(:name), :id, :name, {}, { class: 'form-control' }) %>
  </div>

  <div class="row">
    <div class="field col-sm-6">
      <%= f.label :lesson_number, "Lesson Number*" %><br>
      <%= f.number_field :lesson_number, class: 'form-control' %>
    </div>

    <div class="field col-sm-6">
      <%= f.label :point_value, "Point Value*" %><br>
      <%= f.number_field :point_value, class: 'form-control' %>
    </div>
  </div> <!-- row -->

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: 'form-control' %>
  </div>

  <div class="row">
    <div class="field col-sm-5">
      <%= f.label :started_on %><br>
      <%= f.date_field :started_on, class: 'form-control' %>
    </div>

    <div class="field col-sm-5">
      <%= f.label :completed_on %><br>
      <%= f.date_field :completed_on, class: 'form-control' %>
    </div>

    <div class="field col-sm-2 checkbox">
      <%= f.label :paused %><br>
      <%= f.check_box :paused %>
    </div>
  </div> <!-- row -->

  <div class="actions">
    <%= f.submit class: button_classes('success') %>
  </div>

<% end %> <!-- form_for @task -->

app/views/tasks/_navbar.html.erb
<header>
<h1> The Taskmaster 5000 </h1>
<%= link_to "All Tasks", tasks_path %>
<%= link_to "New Task", new_task_path %>
</header>

app/views/tasks/_new.html.erb
<div class="card card-body">

  <h3>New Task <%= link_to 'Cancel', tasks_path, class: button_classes('warning right') %></h3>

  <%= render partial: 'form', locals: {task: @task} %>

</div> <!-- card card-body -->

app/views/tasks/_sticky.html.erb
<li>
	<span <%= sticky.done ? " class=done" : '' %>><%= sticky.title %> [<b><%= sticky.importance %></b>]</span><br>
<%= link_to "Details", task_path(sticky) %> <%= link_to "Edit", edit_task_path(sticky) %> <%= link_to "Delete", task_path(sticky), method: :delete, data: { confirm: 'Are you sure?'} %> <%= link_to "Toggle Done", task_done_path(sticky), method: :patch %> <%= link_to "SMS Task", send_text_path(sticky) %>
</li>

app/views/tasks/_task_form.html.erb
<%= form_for task do |f| %>
  <%= f.label "Task" %>
  <%= f.text_field :description %>
  <br>
  <%= f.label "Completion Date" %>
  <%= f.text_field :completion_date %>
  <br>
  <%= f.label "Priority" %>
  <select name="task[priority]">
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
  </select>
  <%= f.submit %>
<% end %>

app/views/tasks/_task_list.html.erb
<ul>
<% tasks.each do |task| %>
  <li>
  <% if task.completed %>
    <strike> <%= task.title %> </strike>
    <%= link_to "undo", complete_path(task), :method => :post %>
  <% else %>

    <% if task.priority == 6 %>
      <span style="background-color: yellow; border:solid"> <%= task.title %> </span>
    <% else %>
      <%= task.priority %>
      <%= link_to "#{task.title}", task %>
    <% end %>
    
    <%= link_to "edit", edit_task_path(task) %>
    <%= link_to "complete", complete_path(task), :method => :post %>
    <%= link_to "reminder", reminder_path(task), :method => :post %>
    <%= link_to "sticky", task_path(task, :sticky => true), method: "put" %>
  <% end %>
  <%= link_to "delete", task, :method => :delete %>
  </li>
<% end %>
</ul>

app/views/tasks/_task_output.html.erb
<% if task.complete %>
  <p style="text-decoration: line-through">
    <%= link_to task.title, task %>
    <br>
    <%= task.deadline %>
<% else %>
  <p>
    <%= link_to task.title, task %>
    <br>
    <%= task.deadline %>
<% end %>
<br>
Rating: <%= task.rating %>
<br>
<%= link_to "Delete", task_path(task), method: :delete %>
<%= link_to "Completed", task_path(task), method: :post %>
<%= link_to "Edit", edit_task_path(task) %>
<%= link_to "Send Reminder", text_path(task) %>
</p>

app/views/tasks/_tasks.html.erb
<% tasks.each do |task| %>
  <p>
    <strong><%= link_to task.title, task_path(task.id) %></strong>

    [<%= link_to "Delete", task_path(task.id), :method => :delete %>] |
    [<%= link_to "Edit", edit_task_path(task.id) %>]
  </p>

  <p>

  </p>

<% end %>

app/views/tasks/edit.js.erb
console.log('edit.js.erb reporting for duty')

let task = document.querySelector("#<%= dom_id(@task) %>")

task.insertAdjacentHTML('beforeend', "<%= escape_javascript(render partial: 'edit', locals: {task: @task} ) %>")

app/views/tasks/index.html.erb
<div class="right">
  <%= link_to 'New Task', new_task_path, remote: true, class: button_classes %>
</div> <!-- right -->

<h1>Tasks</h1>

<div id="form_placeholder"></div>

<div class="row" id="stats_section">
  <%= render partial: 'stats', locals: {task_set: @task_set} %>
</div> <!-- row -->

<div class="row" id="tasks-section">
  <div class="col-12">

    <%= render_task_set('Current Task', @task_set.current, 'current') %>

    <%= render_task_set('To Do', @task_set.to_do, 'todo') %>

    <%= render_task_set('Completed Tasks', @task_set.completed, 'completed') %>

  </div> <!-- col-12 -->
</div> <!-- row -->

app/views/tasks/new.js.erb
console.log('new.js.erb reporting for duty')

let statsSection = document.querySelector('#stats_section')
statsSection.classList.add('hidden')

let formPlaceholder = document.querySelector('#form_placeholder')
formPlaceholder.innerHTML = "<%= escape_javascript(render partial: 'new' ) %>"

app/views/tasks/update.js.erb
console.log('update.js.erb reporting for duty')

let task = document.querySelector("#<%= dom_id(@task) %>")
task.outerHTML = "<%= escape_javascript(render partial: 'task', locals: { task: @task } ) %>"

let statsSection = document.querySelector('#stats_section')
statsSection.innerHTML = "<%= escape_javascript(render partial: 'stats', locals: { task_set: @task_set } ) %>"