config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'
  devise_for :users
  resources :tasks
  resources :favorites, only: [:create, :destroy]
  resources :categories, only: [:index]

end

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div>
    <strong><%= type %>! <%= message %></strong>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= bootstrap_flash_class(type) %> fadein">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden=true>&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
  </div>
</footer>

app/views/shared/_form.html.erb
<%= form_for @task do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %><br>

  <%= f.label :deadline %>
  <%= f.date_select :deadline %><br>
  <%= f.submit %>

<% end %>

app/views/shared/_mark_complete.html.erb
<%= form_for task do |f| %>
  <%= f.hidden_field :completed, value: !task.completed %>
  <%= f.submit (task.completed ? "Mark Incomplete" : "Mark Complete" ) %>
<% end %>

app/views/shared/_nav.html.erb
<ul>
  <li><%= link_to "Tasks Index", tasks_path %></li>
  <li><%= link_to "Create Task", new_task_path %></li>
</ul>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light">
  <%= link_to (image_tag 'favicon.png'), root_path %><%= link_to 'Progress Tracker', root_url, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to 'Curriculum', categories_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Tasks', tasks_path, class: 'nav-link' %></li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Edit profile', edit_user_registration_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item"><%= link_to "Log In", new_user_session_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </div><!-- collapse -->
</nav>

app/views/shared/_task_display.html.erb
<ul>
  <li><%= task.category %> </li>
  <li><%= "Priority #{task.priority}" %></li>
  <% if task.soft_delete %>
    <li><s><%= task.description %></s></li>
  <% else %>
    <li><%= task.description %></li>
  <% end %>
  <%= content_tag(:li,task.completed_at) if task.completed_at %>
</ul>
<form action="<%= reminder_path %>"  method="post">
  <input type="hidden" name="task[id]" value="<%= task.id %>" />
  <input type="hidden" name="authenticity_token"  value="<%= form_authenticity_token %>">
  <input type="submit" value="Send text" />
</form>

app/views/shared/_task_form.html.erb
<%= form_for task do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.submit %>
<% end %>

app/views/shared/_text.html.erb
<form method="post" action="/texts/send_text/<%= task.id %>">
  <input  type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
  <input type="submit" value="Remind Me!">
</form>

app/views/shared/_title.html.erb
<div class="top-title">
  <h1>Task Manager</h1>
  <h6>Created by Bran & Deepak</h6>
</div>